Update sha1.cpp Bug Fix for Arduino IDE above 1.5
This is the modification for the issue of:
 sha1.cpp:11:25: error: variable 'sha1InitState' must be const in order to be put into read-only section by means of 'attribute((progmem))' uint8_t sha1InitState[] PROGMEM = { ^ 
This is due to deprecataions and changes in gcc version. this needs to be changed to const .
As of this writing I was using Version1.6.4.